"""Quiz table

Revision ID: b34c7e8ed962
Revises: e9072b3f992a
Create Date: 2022-05-20 21:14:33.531411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34c7e8ed962'
down_revision = 'e9072b3f992a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('equation', sa.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz')
    # ### end Alembic commands ###
