"""redesign db

Revision ID: 191f8b2cf2c0
Revises: 0717e0050e16
Create Date: 2022-05-28 23:08:39.142036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191f8b2cf2c0'
down_revision = '0717e0050e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('success', sa.Boolean(), nullable=True))
    op.drop_column('game', 'outcome')
    op.add_column('user', sa.Column('username', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('played', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('current_streak', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('big_tree', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('tree', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('plant', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('small_plant', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('seed_', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'seed_')
    op.drop_column('user', 'small_plant')
    op.drop_column('user', 'plant')
    op.drop_column('user', 'tree')
    op.drop_column('user', 'big_tree')
    op.drop_column('user', 'current_streak')
    op.drop_column('user', 'played')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'username')
    op.add_column('game', sa.Column('outcome', sa.NUMERIC(), nullable=True))
    op.drop_column('game', 'success')
    # ### end Alembic commands ###
