"""refactor user table

Revision ID: 3b3e3c3fce2c
Revises: 191f8b2cf2c0
Create Date: 2022-05-30 00:14:33.014582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b3e3c3fce2c'
down_revision = '191f8b2cf2c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('date', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
